In [ ]:
# !pip install selenium==3.14.1
# !pip install selenium --upgrade

In [1]:
import pandas as pd

In [8]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys  # 폴더 경로 안에 있는 Keys 모듈 사용
import time  # 시간 변수 사용
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By

# 크롬 드라이버 사용을 위해 크롬 버전 확인 필요
# (...에 도움말 - Chrome 정보 - 버전 확인 후 버전에 맞는 크롬 드라이버 다운로드)
driver_path = 'C:/Users/enduser/Python Basic/semi_project/chromedriver.exe'
driver = webdriver.Chrome(driver_path)

C:\Users\enduser\AppData\Local\Temp\ipykernel_21644\2034472421.py:11: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(driver_path)

In [11]:
url = 'https://www.kave.or.kr/new_statistics/quant_list.php'
driver.get(url)

In [ ]:
# 찾고자 하는 데이터의 id나 class를 먼저 찾는다(복사한 id나 class에 공백이 있는 경우 지우고 .으로 바꿔줘야 함)
# id는 보통 하나만 쓰지만, class의 경우 여러번 사용할 수 있기 때문에 element -> elemnets로 먼저 찍어본다

In [12]:
# 년도 선택
select_year = Select(driver.find_element(By.NAME, 'EvalYear'))
select_year.select_by_index(1)

In [13]:
# 드롭박스 항목 개수 확인
test = driver.find_element(By.NAME, 'EvalUniv')
test = test.find_elements(By.TAG_NAME, 'option')
len(test)

133

In [14]:
# 대학교 선택
select_univ = Select(driver.find_element(By.NAME, 'EvalUniv'))
select_univ.select_by_index(2)

In [19]:
tt = driver.find_element(By.CLASS_NAME,'multiselect-dropdown-arrow')
tt.click()

In [20]:
tt2 = driver.find_element(By.CLASS_NAME, 'multiselect-text')
tt2.click()

In [21]:
ss = driver.find_element(By.CLASS_NAME, 'btn_search')
ss.click()

In [24]:
# 대학명 가져오기
title = driver.find_element(By.ID, 'm_title3').text[1:-1]
title

'강릉영동대학교'

In [25]:
tbody = driver.find_element(By.ID, 'listView3')
tr = tbody.find_elements(By.TAG_NAME, 'tr')

In [26]:
len(tr)

12

In [32]:
list_a = []
for i in tr :
    td = i.find_elements(By.TAG_NAME, 'td')
    list_b = []
    for j in td :
        list_b.append(j.text)
    list_a.append(list_b)
list_a

[['1.2.2 교육비 환원율(%)', '122.4', '126.5', '120.1', '123.3', '123.0'],
 ['2.2.1 학생 1인당 실험실습비(천원)', '255.3', '223.9', '169.9', '196.9', '216.4'],
 ['3.1.1 신입생 충원율(%)', '90.3', '78.0', '71.1', '74.6', '79.8'],
 ['3.1.3 재학생 등록유지율(%)', '91.6', '92.8', '95.0', '93.9', '93.1'],
 ['4.1.2 건강보험 및 국세DB 연계 취업률(%)', '74.5', '69.7', '69.7', '69.7', '71.3'],
 ['5.1.1 장학금 지급 비율(%)', '15.6', '15.5', '10.3', '12.9', '13.8'],
 ['5.2.1 학생 1인당 자료구입비(천원)', '22.1', '21.6', '15.6', '18.6', '19.8'],
 ['5.2.2 교사확보율(%)', '163.4', '164.3', '168.8', '166.6', '165.5'],
 ['6.1.1 전임교원 확보율(%)', '64.7', '62.3', '66.1', '64.2', '64.4'],
 ['6.1.3 전임교원 1인당 연구실적(건)', '0.4', '0.6', '0.4', '0.5', '0.5'],
 ['6.2.1 등록금 대비 교원 인건비 비율(%)', '44.5', '44.4', '44.7', '44.6', '44.5'],
 ['6.2.1 등록금 대비 직원 인건비 비율(%)', '17.4', '18.3', '20.2', '19.3', '18.6']]

In [33]:
df = pd.DataFrame(list_a)
df.columns = []
df

                              0      1      2      3      4      5
0              1.2.2 교육비 환원율(%)  122.4  126.5  120.1  123.3  123.0
1        2.2.1 학생 1인당 실험실습비(천원)  255.3  223.9  169.9  196.9  216.4
2              3.1.1 신입생 충원율(%)   90.3   78.0   71.1   74.6   79.8
3            3.1.3 재학생 등록유지율(%)   91.6   92.8   95.0   93.9   93.1
4   4.1.2 건강보험 및 국세DB 연계 취업률(%)   74.5   69.7   69.7   69.7   71.3
5            5.1.1 장학금 지급 비율(%)   15.6   15.5   10.3   12.9   13.8
6        5.2.1 학생 1인당 자료구입비(천원)   22.1   21.6   15.6   18.6   19.8
7                5.2.2 교사확보율(%)  163.4  164.3  168.8  166.6  165.5
8             6.1.1 전임교원 확보율(%)   64.7   62.3   66.1   64.2   64.4
9        6.1.3 전임교원 1인당 연구실적(건)    0.4    0.6    0.4    0.5    0.5
10    6.2.1 등록금 대비 교원 인건비 비율(%)   44.5   44.4   44.7   44.6   44.5
11    6.2.1 등록금 대비 직원 인건비 비율(%)   17.4   18.3   20.2   19.3   18.6

## 전체 코드

In [35]:
select_year = Select(driver.find_element(By.NAME, 'EvalYear'))
select_year.select_by_index(1)

tt = driver.find_element(By.CLASS_NAME,'multiselect-dropdown-arrow')
tt.click()
time.sleep(0.5)

tt2 = driver.find_element(By.CLASS_NAME, 'multiselect-text')
tt2.click()
time.sleep(0.5)

list_a = []
for i in range(2) :
    select_univ = Select(driver.find_element(By.NAME, 'EvalUniv'))
    select_univ.select_by_index(i)
    time.sleep(0.5)
    
#     tt = driver.find_element(By.CLASS_NAME,'multiselect-dropdown-arrow')
#     tt.click()
#     time.sleep(0.5)
    
#     tt2 = driver.find_element(By.CLASS_NAME, 'multiselect-text')
#     tt2.click()
#     time.sleep(0.5)
    
    ss = driver.find_element(By.CLASS_NAME, 'btn_search')
    ss.click()
    time.sleep(0.5)
    
    tbody = driver.find_element(By.ID, 'listView3')
    tr = tbody.find_elements(By.TAG_NAME, 'tr')
    
    for j in tr :
        td = j.find_elements(By.TAG_NAME, 'td')
        list_b = []
        for k in td :
            list_b.append(k.text)
        list_a.append(list_b)

df = pd.DataFrame(list_a)
df

                              0      1      2      3      4      5
0              1.2.2 교육비 환원율(%)  189.4  173.1  161.4  167.3  174.6
1        2.2.1 학생 1인당 실험실습비(천원)  176.2  156.1  168.9  162.5  167.1
2              3.1.1 신입생 충원율(%)   94.4   91.0   82.6   86.8   89.3
3            3.1.3 재학생 등록유지율(%)   91.6   89.3   87.2   88.3   89.4
4   4.1.2 건강보험 및 국세DB 연계 취업률(%)   79.3   78.1   80.3   79.2   79.2
5            5.1.1 장학금 지급 비율(%)   21.6   20.9   18.0   19.5   20.2
6        5.2.1 학생 1인당 자료구입비(천원)   33.8   33.7   34.1   33.9   33.9
7                5.2.2 교사확보율(%)  196.3  192.7  191.7  192.2  193.6
8             6.1.1 전임교원 확보율(%)   60.7   59.8   62.5   61.2   61.0
9        6.1.3 전임교원 1인당 연구실적(건)    0.3    0.4    0.9    0.7    0.5
10    6.2.1 등록금 대비 교원 인건비 비율(%)   39.7   40.0   39.5   39.8   39.7
11    6.2.1 등록금 대비 직원 인건비 비율(%)   20.7   23.1   22.1   22.6   22.0
12             1.2.2 교육비 환원율(%)  142.0  150.4  150.4  150.4  147.6
13       2.2.1 학생 1인당 실험실습비(천원)  197.5  212.1  196.9  204.5  202.2
14             3.1.1 신입생 충원율(%)   97.3   80.2   61.7   71.0   79.7
15           3.1.3 재학생 등록유지율(%)   95.8   94.7   94.2   94.5   94.9
16  4.1.2 건강보험 및 국세DB 연계 취업률(%)   67.4   71.6   67.4   69.5   68.8
17           5.1.1 장학금 지급 비율(%)   16.3   15.3   16.2   15.8   15.9
18       5.2.1 학생 1인당 자료구입비(천원)   27.8   23.8   22.3   23.1   24.6
19               5.2.2 교사확보율(%)  123.0  121.9  143.3  132.6  129.4
20            6.1.1 전임교원 확보율(%)   58.2   57.3   56.1   56.7   57.2
21       6.1.3 전임교원 1인당 연구실적(건)    0.3    0.2    0.1    0.2    0.2
22    6.2.1 등록금 대비 교원 인건비 비율(%)   41.8   42.6   43.3   43.0   42.6
23    6.2.1 등록금 대비 직원 인건비 비율(%)   11.8   11.5   12.2   11.9   11.8